const categorias = [
  {
    nombre: "TV en Vivo",
    canales: [
      // ===== LATINOAMERICA =====
      { nombre: "ESPN", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn", logo: "", live: true },
      { nombre: "ESPN 2", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn2", logo: "", live: true },
      { nombre: "ESPN 3", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn3", logo: "", live: true },
      { nombre: "ESPN 4", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn4", logo: "", live: true },
      { nombre: "ESPN 5", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn5", logo: "", live: true },
      { nombre: "ESPN 6", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn6", logo: "", live: true },
      { nombre: "ESPN 7", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn7", logo: "", live: true },
      { nombre: "DSports", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=dsports", logo: "", live: true },
      { nombre: "DSports 2", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=dsports2", logo: "", live: true },
      { nombre: "DSports Plus", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=dsportsplus", logo: "", live: true },
      { nombre: "GOLTV", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=goltv", logo: "", live: true },
      { nombre: "ECDF LigaPro (eventos)", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=ecdf_ligapro", logo: "", live: true },

      // ===== ARGENTINA =====
      { nombre: "Fox Sports", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsports", logo: "", live: true },
      { nombre: "Fox Sports 2", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsports2", logo: "", live: true },
      { nombre: "Fox Sports 3", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsports3", logo: "", live: true },
      { nombre: "TNT Sports", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=tntsports", logo: "", live: true },
      { nombre: "ESPN Premium", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espnpremium", logo: "", live: true },
      { nombre: "TyC Sports", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=tycsports", logo: "", live: true },
      { nombre: "TyC Sports Internacional (USA)", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=tycinternacional", logo: "", live: true },

      // ===== PERÚ =====
      { nombre: "Movistar Deportes", pais: "PERÚ", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=movistar", logo: "", live: true },

      // ===== COLOMBIA =====
      { nombre: "Win Sports Plus", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=winsportsplus", logo: "", live: true },
      { nombre: "Win Sports", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=winsports", logo: "", live: true },

      // ===== MÉXICO =====
      { nombre: "Fox Sports MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsportsmx", logo: "", live: true },
      { nombre: "Fox Sports 2 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsports2mx", logo: "", live: true },
      { nombre: "Fox Sports 3 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsports3mx", logo: "", live: true },
      { nombre: "Fox Sports Premium", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxsportspremium", logo: "", live: true },
      { nombre: "ESPN MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espnmx", logo: "", live: true },
      { nombre: "ESPN 2 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn2mx", logo: "", live: true },
      { nombre: "ESPN 3 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn3mx", logo: "", live: true },
      { nombre: "ESPN 4 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espn4mx", logo: "", live: true },
      { nombre: "Azteca 7", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=azteca7", logo: "", live: true },
      { nombre: "TVC Deportes", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=tvc_deportes", logo: "", live: true },
      { nombre: "Azteca Deportes", pais: "MÉXICO", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=azteca_deportes", logo: "", live: true },

      // ===== USA =====
      { nombre: "Fox Deportes", pais: "USA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=foxdeportes", logo: "", live: true },
      { nombre: "ESPN Deportes", pais: "USA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=espndeportes", logo: "", live: true },
      { nombre: "TUDN USA", pais: "USA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=tudn", logo: "", live: true },
      { nombre: "BeIN Sports Xtra Español", pais: "USA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=beinsport_xtra_espanol", logo: "", live: true },
      { nombre: "USAnetwork", pais: "USA", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=usanetwork", logo: "", live: true },

      // ===== BRASIL =====
      { nombre: "Premiere 1", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere1", logo: "", live: true },
      { nombre: "Premiere 2", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere2", logo: "", live: true },
      { nombre: "Premiere 3", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere3", logo: "", live: true },
      { nombre: "Premiere 4", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere4", logo: "", live: true },
      { nombre: "Premiere 5", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere5", logo: "", live: true },
      { nombre: "Premiere 6", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=premiere6", logo: "", live: true },
      { nombre: "Sportv", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=sportv", logo: "", live: true },
      { nombre: "Sportv 2", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=sportv2", logo: "", live: true },
      { nombre: "Sportv 3", pais: "BRASIL", programa: "Deportes en directo", video: "https://la14hd.com/vivo/canales.php?stream=sportv3", logo: "", live: true },

      // ===== CANALES STREAMTP10 =====
      { nombre: "ESPN 1", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn", logo: "", live: true },
      { nombre: "ESPN 2", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn2", logo: "", live: true },
      { nombre: "ESPN 3", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn3", logo: "", live: true },
      { nombre: "ESPN 4", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn4", logo: "", live: true },
      { nombre: "ESPN 5", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn5", logo: "", live: true },
      { nombre: "ESPN 6", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn6", logo: "", live: true },
      { nombre: "ESPN 7", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn7", logo: "", live: true },
      { nombre: "Win Sports +", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=winplus", logo: "", live: true },
      { nombre: "Win Sports + (Op2)", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=winplus2", logo: "", live: true },
      { nombre: "Win Sports", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=winsports", logo: "", live: true },
      { nombre: "Win Play +", pais: "COLOMBIA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=winplusonline1", logo: "", live: true },
      { nombre: "Fox Sports 1 (Argentina)", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox1ar", logo: "", live: true },
      { nombre: "Fox Sports 2 (Argentina)", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox2ar", logo: "", live: true },
      { nombre: "Fox Sports 3 (Argentina)", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox3ar", logo: "", live: true },
      { nombre: "Dsports", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=dsports", logo: "", live: true },
      { nombre: "Dsports 2", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=dsports2", logo: "", live: true },
      { nombre: "Dsports +", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=dsportsplus", logo: "", live: true },
      { nombre: "TNT Sports Chile", pais: "CHILE", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tntsportschile", logo: "", live: true },
      { nombre: "TNT Sports Argentina", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tntsports", logo: "", live: true },
      { nombre: "ESPN Premium Argentina", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espnpremium", logo: "", live: true },
      { nombre: "TyC Sports", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tycsports", logo: "", live: true },
      { nombre: "Telefe", pais: "ARGENTINA", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=telefe", logo: "", live: true },
      { nombre: "TV Pública", pais: "ARGENTINA", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=tv_publica", logo: "", live: true },
      { nombre: "Liga 1 MAX", pais: "PERÚ", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=liga1max", logo: "", live: true },
      { nombre: "GolTV", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=goltv", logo: "", live: true },
      { nombre: "VTV +", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=vtvplus", logo: "", live: true },
      { nombre: "ESPN Deportes USA", pais: "USA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espndeportes", logo: "", live: true },
      { nombre: "TUDN USA", pais: "USA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tudn_usa", logo: "", live: true },
      { nombre: "Fox Sports 1 USA", pais: "USA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox_1_usa", logo: "", live: true },
      { nombre: "Fox Sports 2 USA", pais: "USA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox_2_usa", logo: "", live: true },
      { nombre: "Universo USA", pais: "USA", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=universo_usa", logo: "", live: true },
      { nombre: "Univisíon USA", pais: "USA", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=univision_usa", logo: "", live: true },
      { nombre: "Fox Deportes USA", pais: "USA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox_deportes_usa", logo: "", live: true },
      { nombre: "Azteca 7 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=azteca7", logo: "", live: true },
      { nombre: "Fox Sports 1 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=foxsportsmx", logo: "", live: true },
      { nombre: "Fox Sports 2 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=foxsports2mx", logo: "", live: true },
      { nombre: "Fox Sports 3 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=foxsports3mx", logo: "", live: true },
      { nombre: "Fox Sports Premium", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=foxsportspremium", logo: "", live: true },
      { nombre: "ESPN MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espnmx", logo: "", live: true },
      { nombre: "ESPN 2 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn2mx", logo: "", live: true },
      { nombre: "ESPN 3 MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=espn3mx", logo: "", live: true },
      { nombre: "Fox ONE MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=foxone", logo: "", live: true },
      { nombre: "Fox MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=fox", logo: "", live: true },
      { nombre: "USA Network", pais: "USA", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=usa_network", logo: "", live: true },
      { nombre: "TyC Sports Internacional", pais: "ARGENTINA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tycinternacional", logo: "", live: true },
      { nombre: "Canal 5 MX", pais: "MÉXICO", programa: "Entretenimiento en directo", video: "https://streamtp10.com/global1.php?stream=canal5mx", logo: "", live: true },
      { nombre: "TUDN MX", pais: "MÉXICO", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tudnmx", logo: "", live: true },
      { nombre: "FUTV (Eventos)", pais: "LATINOAMERICA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=futv", logo: "", live: true },
      { nombre: "LaLiga Hypermotion", pais: "ESPANA", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=laligahypermotion", logo: "", live: true },
      { nombre: "Tigo Sports Paraguay (Eventos)", pais: "PARAGUAY", programa: "Deportes en directo", video: "https://streamtp10.com/global1.php?stream=tigosportsparaguay", logo: "", live: true },
    ]
  }
];
